[2022-10-04T08:06:48.155+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.insert_data manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:06:48.178+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.insert_data manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:06:48.179+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:06:48.179+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:06:48.179+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:06:48.215+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2022-10-04 08:01:57.419903+00:00
[2022-10-04T08:06:48.222+0000] {standard_task_runner.py:54} INFO - Started process 11655 to run task
[2022-10-04T08:06:48.228+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v1', 'insert_data', 'manual__2022-10-04T08:01:57.419903+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp4vzaw5l3']
[2022-10-04T08:06:48.230+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask insert_data
[2022-10-04T08:06:48.232+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:06:48.522+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v1.insert_data manual__2022-10-04T08:01:57.419903+00:00 [running]> on host e877189be071
[2022-10-04T08:06:48.964+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v1
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:01:57.419903+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:01:57.419903+00:00
[2022-10-04T08:06:48.984+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:06:49.010+0000] {sql.py:315} INFO - Running statement: 
        
        , parameters: None
[2022-10-04T08:06:49.019+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.ProgrammingError: can't execute an empty query
[2022-10-04T08:06:49.039+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v1, task_id=insert_data, execution_date=20221004T080157, start_date=20221004T080648, end_date=20221004T080649
[2022-10-04T08:06:49.067+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task insert_data (can't execute an empty query; 11655)
[2022-10-04T08:06:49.083+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T08:06:49.124+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
