[2022-10-04T08:07:01.662+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:07:01.685+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:07:01.685+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:07:01.685+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2022-10-04T08:07:01.686+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:07:01.722+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-04 08:01:57.419903+00:00
[2022-10-04T08:07:01.729+0000] {standard_task_runner.py:54} INFO - Started process 11686 to run task
[2022-10-04T08:07:01.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v1', 'create_table', 'manual__2022-10-04T08:01:57.419903+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpipiu_8gt']
[2022-10-04T08:07:01.737+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask create_table
[2022-10-04T08:07:01.739+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:07:02.029+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [running]> on host e877189be071
[2022-10-04T08:07:02.379+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v1
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:01:57.419903+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:01:57.419903+00:00
[2022-10-04T08:07:02.399+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:07:02.425+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-10-04T08:07:02.437+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-10-04T08:07:02.460+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v1, task_id=create_table, execution_date=20221004T080157, start_date=20221004T080701, end_date=20221004T080702
[2022-10-04T08:07:02.510+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-04T08:07:02.554+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
